// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epdpkflyodaswskvnknq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZHBrZmx5b2Rhc3dza3Zua25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTg5NzUsImV4cCI6MjA2OTYzNDk3NX0.jeshDp68Ms7pXs-2lvdYHXJtUdAm2r1aelxQ7mkpOoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});